//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eddie.Lib.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eddie.Lib.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;provider title=&quot;AirVPN&quot; website=&quot;https://airvpn.org&quot; class=&quot;service&quot; fetch_mode=&quot;rsa4096+aes256&quot;&gt;
        ///  &lt;manifest&gt;
        ///    &lt;urls&gt;
        ///      &lt;url address=&quot;http://54.93.175.114&quot; /&gt;
        ///	  &lt;url address=&quot;http://54.246.124.152&quot; /&gt;
        ///	  &lt;url address=&quot;http://54.225.156.17&quot; /&gt;
        ///		&lt;url address=&quot;http://95.211.138.143&quot; /&gt;
        ///
        ///    &lt;/urls&gt;
        ///    &lt;rsa&gt;
        ///      &lt;RSAParameters&gt;
        ///        &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///        &lt;Modulus&gt;wuQXz7eZeEBwaaRsVK8iEHpueXoKyQzW8sr8qMUkZIcKtKv5iseXMrTbcGYGpRXdiqXp7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirVPN {
            get {
                return ResourceManager.GetString("AirVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;RSAParameters xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///  &lt;Modulus&gt;wuQXz7eZeEBwaaRsVK8iEHpueXoKyQzW8sr8qMUkZIcKtKv5iseXMrTbcGYGpRXdiqXp7FqrSjPSMDuRGaHfjWgjbnW4PwecmgJSfhkWt4xY8OnIwKkuI2Eo0MAa9lduPOQRKSfa9I1PBogIyEUrf7kSjcoJQgeY66D429m1BDWY3f65c+8HrCQ8qPg1GY+pSxuwp6+2dV7fd1tiKLQEoJg9NeWGW0he/DDkNSe4c8gFfHj3ANYwDhTQijb+VaVZqPmxVJIzLoE1JOom0/P8fKsvpx3cFOtDS4apiI+N7MyVAMcx5Jjk2AQ/tyD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to take  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;manifest&gt;
        ///  &lt;hosts&gt;
        ///		&lt;host address=&quot;54.93.175.114&quot; /&gt;
        ///		&lt;host address=&quot;54.246.124.152&quot; /&gt;
        ///		&lt;host address=&quot;54.225.156.17&quot; /&gt;
        ///		&lt;host address=&quot;95.211.138.143&quot; /&gt;
        ///	&lt;/hosts&gt;        ///  &lt;skins&gt;        ///    &lt;skin name=&quot;Default&quot;&gt;        ///              ///    &lt;/skin&gt;        ///  &lt;/skins&gt;        ///
        ///&lt;/manifest&gt;.
        /// </summary>
        internal static string Manifest {
            get {
                return ResourceManager.GetString("Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------
        ///OpenVPN -- A Secure tunneling daemon
        ///
        ///
        ///
        ///Copyright (C) 2002-2010 OpenVPN Technologies, Inc. 
        ///This program is free software;
        ///
        ///you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License version 2
        ///as published by the Free Software Foundation.
        ///
        ///
        ///
        ///For the latest version of OpenVPN, 
        ///go to:
        ///
        ///	http://openvpn.net/
        ///
        ///License: GNU General Public License (GPL v2+)
        ///--------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirdParty {
            get {
                return ResourceManager.GetString("ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE READ CAREFULLY THE TERMS AND CONDITIONS OF THIS AGREEMENT. BY USING THE SERVICE YOU ACKNOWLEDGE THAT YOU ARE ACCEPTING A BENEFIT BY USING THE SERVICE, AND THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU ARE NOT ALLOWED TO USE THE SERVICE.
        ///
        ///
        ///DESCRIPTION OF SERVICE
        ///
        ///a) AirVPN is operated by Air. Please refer to Privacy Notice for contact details.
        ///
        ///b) AirVPN is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TOS {
            get {
                return ResourceManager.GetString("TOS", resourceCulture);
            }
        }
    }
}
