//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.CLI.Windows.Elevated.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.CLI.Windows.Elevated.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;78gwMqOjS1sfWNFZxmHy8VloO0FalTsvld9wAy8YuQLo3TuUAbPfRFdf9j6UUBnfmU/GSTKK0vAP5IZdq4VOMsQ6mPrF/goNShfvKIAZeHFcl3UwM6vp7+5vTg1Rykt1EkG6dS1E4wCa87G8CVNmZkxxu97Ih/UQ1bZc6cOwEYpRSUocrTXjCkkODWDulLwDBu6stu/GVOug78bbs54/atyVSkE721efISrHrE8iN50Xmx3BME/6yFtie+EL9ztXmMekDw8Zc9u9Gu3nMS9yHF8NqYRa0m/Nfr++LkJORv1dAlVI2HOoNiyYzyOUzAoGpR1ijhADnlmyB6Lfbb19z7JFncpYw0SZCRkMf1OL2Ds5xNAVjD3mzgMl0YDEIJT6PLOuyKmNrhLddY5KPWaQmoOihnRhUOnKlfsAloG7AhLgvXMWBWCS3nzi5n2N0RFemoiM65LqnVIzTfbDfppUaM03z0MrcOpKFTwyUIXsHe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eddie_file_public_xml {
            get {
                return ResourceManager.GetString("eddie_file_public_xml", resourceCulture);
            }
        }
    }
}
